<?php

global  $wpdb ;
$sql[] = "CREATE TABLE " . $wpdb->prefix . "ds_classes (\n  id bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,\n  name varchar(250) NOT NULL,\n  class_fee float(5,2) NOT NULL,\n  costume_fee float(5,2) NOT NULL DEFAULT '65.00',\n  category_id bigint(20) NOT NULL,\n  woocommerce_id bigint(20) NOT NULL,\n  classroom varchar(250) NOT NULL,\n  ages varchar(100) NOT NULL,\n  experience int(3) NOT NULL DEFAULT '0',\n  description text,\n  startdate date NOT NULL,\n  enddate date NOT NULL,\n  days varchar(50) NOT NULL,\n  starttime time NOT NULL,\n  endtime time NOT NULL,\n  is_parent_event int(11) NOT NULL,\n  parent_id int(10) UNSIGNED DEFAULT NULL,\n  is_competitive tinyint(4) NOT NULL DEFAULT '0',\n  is_registerable tinyint(1) DEFAULT NULL,\n  use_global_installments tinyint(1) UNSIGNED DEFAULT '0' NOT NULL,\n  sessions_id smallint(5) UNSIGNED DEFAULT NULL,\n  PRIMARY KEY  (id),\n  KEY parent_id (parent_id),\n  KEY sessions_id (sessions_id),\n  KEY woocommerce_id (woocommerce_id)\n) ENGINE=InnoDB DEFAULT CHARSET=latin1;";
$sql[] = "CREATE TABLE " . $wpdb->prefix . "ds_class_categories (\n  id bigint(20) NOT NULL AUTO_INCREMENT,\n  category_name varchar(250) NOT NULL,\n  sessions_id smallint(5) UNSIGNED DEFAULT NULL,\n  PRIMARY KEY  (id)\n) ENGINE=InnoDB DEFAULT CHARSET=latin1;";
$sql[] = "CREATE TABLE " . $wpdb->prefix . "ds_class_students (\n  id bigint(20) NOT NULL AUTO_INCREMENT,\n  class_id bigint(20) NOT NULL,\n  student_id bigint(20) NOT NULL,\n  week_day tinyint(4) NOT NULL,\n  sessions_id smallint(5) UNSIGNED DEFAULT NULL,\n  PRIMARY KEY (id),\n  UNIQUE KEY student_class_day (class_id,student_id,week_day),\n  KEY week_day (week_day)\n) ENGINE=InnoDB DEFAULT CHARSET=latin1;";
$sql[] = "CREATE TABLE " . $wpdb->prefix . "ds_class_teachers (\n  id bigint(20) NOT NULL AUTO_INCREMENT,\n  firstname varchar(250) NOT NULL,\n  lastname varchar(250) NOT NULL,\n  sessions_id smallint(5) UNSIGNED DEFAULT NULL,\n  PRIMARY KEY  (id)\n) ENGINE=InnoDB DEFAULT CHARSET=latin1;";
$sql[] = "CREATE TABLE " . $wpdb->prefix . "ds_course_recommendations (\n  id int(10) UNSIGNED NOT NULL AUTO_INCREMENT,\n  student_id bigint(20) UNSIGNED NOT NULL,\n  course_id bigint(20) UNSIGNED NOT NULL,\n  sessions_id smallint(5) UNSIGNED NOT NULL,\n  PRIMARY KEY  (id)\n) ENGINE=InnoDB DEFAULT CHARSET=latin1;";
$sql[] = "CREATE TABLE " . $wpdb->prefix . "ds_deactivation_history (\n  id int(10) UNSIGNED NOT NULL AUTO_INCREMENT,\n  student_id int(11) DEFAULT NULL,\n  parent_id int(11) DEFAULT NULL,\n  deactivated timestamp NULL DEFAULT NULL,\n  activated timestamp NULL DEFAULT NULL,\n  PRIMARY KEY  (id),\n  KEY student_id (student_id,parent_id)\n) ENGINE=InnoDB DEFAULT CHARSET=latin1;";
$sql[] = "CREATE TABLE " . $wpdb->prefix . "ds_events (\n  id bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,\n  name varchar(255) NOT NULL,\n  venue_id bigint(20) UNSIGNED NOT NULL,\n  starts timestamp NULL DEFAULT NULL,\n  ends timestamp NULL DEFAULT NULL,\n  ticket_price decimal(7,2) UNSIGNED NOT NULL,\n  max_tickets int(10) UNSIGNED NOT NULL,\n  description text,\n  image_url text CHARACTER SET utf8 COLLATE utf8_bin,\n  meta text,\n  PRIMARY KEY  (id),\n  KEY venue_id (venue_id)\n) ENGINE=InnoDB DEFAULT CHARSET=latin1;";
$sql[] = "CREATE TABLE " . $wpdb->prefix . "ds_event_ticket_sales (\n  id bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,\n  event_id bigint(20) UNSIGNED NOT NULL,\n  parent_id bigint(20) NOT NULL,\n  quantity int(3) UNSIGNED NOT NULL,\n  sub_total decimal(7,2) UNSIGNED NOT NULL,\n  tax decimal(7,2) UNSIGNED NOT NULL,\n  total decimal(7,2) UNSIGNED NOT NULL,\n  date_purchased timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY  (id),\n  KEY event_id (event_id),\n  KEY parent_id (parent_id)\n) ENGINE=InnoDB DEFAULT CHARSET=latin1;";
$sql[] = "CREATE TABLE " . $wpdb->prefix . "ds_news (\n  id int(11) NOT NULL AUTO_INCREMENT,\n  title varchar(255) NOT NULL,\n  content text NOT NULL,\n  date int(10) UNSIGNED NOT NULL,\n  sessions_id smallint(5) UNSIGNED DEFAULT NULL,\n  PRIMARY KEY  (id)\n) ENGINE=InnoDB DEFAULT CHARSET=latin1;";
$sql[] = "CREATE TABLE " . $wpdb->prefix . "ds_parents (\n  id bigint(20) NOT NULL AUTO_INCREMENT,\n  firstname varchar(100) NOT NULL,\n  lastname varchar(100) NOT NULL,\n  user_id bigint(20) NOT NULL,\n  user_level varchar(25) NOT NULL,\n  email varchar(80) NOT NULL,\n  address_data text NOT NULL,\n  meta text NOT NULL,\n  is_confirmed tinyint(4) NOT NULL DEFAULT '0',\n  date_added timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  active tinyint(3) UNSIGNED NOT NULL,\n  sessions_id smallint(5) UNSIGNED DEFAULT NULL,\n  PRIMARY KEY  (id),\n  KEY is_confirmed (is_confirmed),\n  KEY sessions_id (sessions_id)\n) ENGINE=InnoDB DEFAULT CHARSET=latin1;";
$sql[] = "CREATE TABLE " . $wpdb->prefix . "ds_parent_group (\n  parent_id int(11) NOT NULL AUTO_INCREMENT,\n  group_id int(11) NOT NULL,\n  sessions_id smallint(5) UNSIGNED DEFAULT NULL,\n  UNIQUE KEY parent_group (parent_id,group_id)\n) ENGINE=InnoDB DEFAULT CHARSET=latin1;";
$sql[] = "CREATE TABLE " . $wpdb->prefix . "ds_sessions (\n  id smallint(5) UNSIGNED NOT NULL AUTO_INCREMENT,\n  name varchar(255) NOT NULL,\n  PRIMARY KEY  (id)\n) ENGINE=InnoDB DEFAULT CHARSET=latin1;";
$sql[] = "CREATE TABLE " . $wpdb->prefix . "ds_students (\n  id bigint(20) NOT NULL AUTO_INCREMENT,\n  firstname varchar(100) NOT NULL,\n  lastname varchar(100) NOT NULL,\n  parent_id bigint(20) NOT NULL,\n  parent2_id int(11) NOT NULL,\n  birthdate date DEFAULT NULL,\n  user_level varchar(25) DEFAULT NULL,\n  gender enum('male','female') NOT NULL,\n  address_data text NOT NULL,\n  measurements text,\n  meta text NOT NULL,\n  date_added timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  is_confirmed tinyint(4) NOT NULL DEFAULT '0',\n  active tinyint(4) NOT NULL DEFAULT '0',\n  can_register_online tinyint(4) NOT NULL DEFAULT '1',\n  schedule_available tinyint(4) NOT NULL DEFAULT '0',\n  sessions_id smallint(5) UNSIGNED DEFAULT NULL,\n  PRIMARY KEY  (id),\n  KEY firstname (firstname),\n  KEY lastname (lastname),\n  KEY parent_id (parent_id),\n  KEY parent2_id (parent2_id),\n  KEY is_confirmed (is_confirmed),\n  KEY sessions_id (sessions_id)\n) ENGINE=InnoDB DEFAULT CHARSET=latin1;";
$sql[] = "CREATE TABLE " . $wpdb->prefix . "ds_students_history (\n  id int(10) UNSIGNED NOT NULL AUTO_INCREMENT,\n  student_id int(10) UNSIGNED NOT NULL,\n  type varchar(255) NOT NULL,\n  value text NOT NULL,\n  value2 text NOT NULL,\n  sessions_id smallint(5) UNSIGNED DEFAULT NULL,\n  PRIMARY KEY  (id)\n) ENGINE=InnoDB DEFAULT CHARSET=latin1;";
$sql[] = "CREATE TABLE " . $wpdb->prefix . "ds_venues (\n  id bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,\n  name varchar(255) NOT NULL,\n  address_data text,\n  meta text,\n  PRIMARY KEY  (id),\n  UNIQUE KEY name (name)\n) ENGINE=InnoDB DEFAULT CHARSET=latin1;";
$sql[] = "CREATE TABLE " . $wpdb->prefix . "ds_countries (\n   id int(11) NOT NULL AUTO_INCREMENT,\n   code varchar(2) NOT NULL,\n   name varchar(100) NOT NULL,\n   PRIMARY KEY  (id),\n   UNIQUE KEY code (code)\n) ENGINE=InnoDB DEFAULT CHARSET=latin1;";